# Generated by Django 4.2.23 on 2025-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
