# Generated by Django 4.2.23 on 2025-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
