# Generated by Django 4.2.21 on 2025-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
