# Generated by Django 4.2.21 on 2025-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_reviewer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_status',
            field=models.CharField(choices=[('reviewed', '✅ Reviewed'), ('needs_changes', '⚠️ Needs Changes'), ('draft', '🕗 Draft')], default='draft', max_length=20),
        ),
    ]
