# Generated by Django 4.2.23 on 2025-09-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='published_on',
        ),
    ]
