# Generated by Django 4.2.21 on 2025-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='premium_post',
            field=models.BooleanField(default=False, help_text='Mark this post as premium content'),
        ),
    ]
